This C code and python interface implements the algorithm described
in the following paper.

Vargovich J and Hocking TD. Linear time dynamic programming for
computing breakpoints in the regularization path of models selected
from a finite set.
- Published in [[https://amstat.tandfonline.com/doi/full/10.1080/10618600.2021.2000422][Journal of Computational and Graphical Statistics]]
  (2021).
- Preprint [[https://arxiv.org/abs/2003.02808][arXiv:2003.02808]].

** Related work

The Python min_label_error function implements computation of 
- (1) current estimate of target interval of log(penalty) values with minimum error. Useful to construct output/target/label matrix when learning a penalty function via interval regression.
- (2) set of penalties which would be interesting to compute next for trying to find the target interval. This set will be empty if the target interval has already been determined, so for learning you can repeatedly call this function and compute penalties and it will eventually stop. 
- These algorithms should be the same as PeakSegPipeline::problem.target in R, https://github.com/tdhock/PeakSegPipeline/blob/master/R/PeakSegFPOP.R (research paper with details of these algorithms in progress).
